# Generated by Django 2.0.3 on 2018-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hyperlink',
            field=models.CharField(default='add hyperlink', max_length=100),
        ),
    ]
