# Generated by Django 2.0.3 on 2018-05-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='add title', max_length=50),
        ),
    ]
